version: '3'

services:
  # Hadoop NameNode - HDFS primary node
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"  # Namenode web UI
      - "9000:9000"  # HDFS client port
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

  # Hadoop DataNode - HDFS data storage
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    ports:
      - "9864:9864"  # Datanode web UI
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
    networks:
      - hadoop_network

  # ResourceManager - YARN Resource Manager for MapReduce
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    ports:
      - "8088:8088"  # Resource Manager web UI
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode
    networks:
      - hadoop_network

  # NodeManager - YARN Node Manager for MapReduce tasks
  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    networks:
      - hadoop_network
      
  # Hive Server - For SQL-like queries on HDFS data
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    restart: always
    ports:
      - "10000:10000"  # Hive Server port
      - "10002:10002"  # Hive Server Web UI
    environment:
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore-postgresql/metastore
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode
      - hive-metastore
    networks:
      - hadoop_network

  # Hive Metastore - Stores metadata for Hive tables
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    restart: always
    environment:
      - SERVICE_PRECONDITION=namenode:9870 hive-metastore-postgresql:5432
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    depends_on:
      - namenode
      - hive-metastore-postgresql
    networks:
      - hadoop_network

  # PostgreSQL database for Hive Metastore
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    restart: always
    volumes:
      - hive_metastore_postgresql:/var/lib/postgresql/data
    networks:
      - hadoop_network

  # Superset - Data visualization platform
  superset:
    image: apache/superset:latest
    container_name: superset
    restart: always
    ports:
      - "8088:8088"  # Superset web UI
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - superset-init
    networks:
      - hadoop_network

  # Initialize Superset database and create admin user
  superset-init:
    image: apache/superset:latest
    container_name: superset-init
    restart: "no"
    depends_on:
      - superset-db
    volumes:
      - superset_home:/app/superset_home
    command: >
      bash -c "superset db upgrade &&
              superset fab create-admin
                        --username admin
                        --firstname Admin
                        --lastname User
                        --email admin@example.com
                        --password admin &&
              superset init"
    networks:
      - hadoop_network

  # PostgreSQL database for Superset
  superset-db:
    image: postgres:13
    container_name: superset-db
    restart: always
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_DB=superset
    volumes:
      - superset_db:/var/lib/postgresql/data
    networks:
      - hadoop_network

  # Redis for Superset caching
  redis:
    image: redis:latest
    container_name: superset-redis
    restart: always
    networks:
      - hadoop_network

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hive_metastore_postgresql:
  superset_home:
  superset_db:

networks:
  hadoop_network:
    driver: bridge